theme: jekyll-theme-minimal
title: ADA Template Website - ImportNumpyAsPd
description: A template website for ADA
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
