theme: jekyll-theme-minimal
title: ADA Template Website - ImportNumpyAsPd
description: A template website for ADA
show_downloads: False

exclude:
  - README.md

navigation:
  - title: Data exploration
    url: introduction
  - title: Example
    url: example
markdown: kramdown
kramdown:
  input: GFM

