theme: jekyll-theme-minimal
title: ADA Template Website - ImportNumpyAsPd
description: A template website for ADA
show_downloads: True
navigation:
  - title: Data exploration
    url: introduction
  - title: Home
    url: /
  - title: Example
    url: example
markdown: kramdown
kramdown:
  input: GFM

